# Generated by Django 5.1.4 on 2026-04-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='器材名称')),
                ('category', models.CharField(choices=[('cardio', '有氧器材'), ('strength', '力量训练器材'), ('functional', '功能性训练器材')], max_length=20, verbose_name='器材类别')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='器材图片')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='视频链接')),
                ('description', models.TextField(blank=True, null=True, verbose_name='器材描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '器材',
                'verbose_name_plural': '器材列表',
                'ordering': ['category', 'name'],
            },
        ),
    ]
