# Generated by Django 5.1.4 on 2026-04-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='输入饮食建议的标题', max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('pre_workout', '健身前饮食'), ('post_workout', '健身后饮食'), ('daily_nutrition', '日常营养'), ('supplement', '营养补剂'), ('tips', '饮食小贴士')], help_text='选择建议所属的类别', max_length=20, verbose_name='类别')),
                ('image', models.ImageField(blank=True, help_text='上传相关图片，支持JPG、PNG格式', null=True, upload_to='diet_images/', verbose_name='配图')),
                ('video_url', models.URLField(blank=True, help_text='输入相关的视频教程链接', max_length=500, null=True, verbose_name='视频链接')),
                ('content', models.TextField(help_text='输入饮食建议的详细内容和说明', verbose_name='详细内容')),
                ('is_featured', models.BooleanField(default=False, help_text='勾选后在首页推荐显示', verbose_name='推荐显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '饮食建议',
                'verbose_name_plural': '饮食建议列表',
                'ordering': ['category', '-created_at'],
            },
        ),
    ]
