# Generated by Django 5.1.4 on 2026-04-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_guide', '0002_dietitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：胸部、背部、肩部、手臂、腿部等', max_length=100, verbose_name='肌肉群名称')),
                ('latin_name', models.CharField(blank=True, help_text='肌肉群的拉丁学名', max_length=100, null=True, verbose_name='拉丁学名')),
                ('category', models.CharField(choices=[('upper', '上肢肌群'), ('core', '核心肌群'), ('lower', '下肢肌群'), ('cardio', '心肺功能')], help_text='选择肌肉群所属的类别', max_length=20, verbose_name='所属大类')),
                ('icon', models.CharField(blank=True, help_text='输入emoji图标，如：💪、🏋️等', max_length=50, null=True, verbose_name='图标')),
                ('description', models.TextField(blank=True, help_text='简要描述该肌肉群的位置和功能', null=True, verbose_name='简要描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '肌肉群',
                'verbose_name_plural': '肌肉群列表',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='dietitem',
            name='category',
            field=models.CharField(choices=[('pre_workout', '健身前饮食'), ('post_workout', '健身后饮食'), ('daily_nutrition', '日常营养'), ('supplement', '营养补剂'), ('tips', '饮食小贴士')], max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='dietitem',
            name='content',
            field=models.TextField(verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='dietitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diet_images/', verbose_name='配图'),
        ),
        migrations.AlterField(
            model_name='dietitem',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='推荐显示'),
        ),
        migrations.AlterField(
            model_name='dietitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='dietitem',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='视频链接'),
        ),
        migrations.CreateModel(
            name='MuscleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：胸大肌、背阔肌、股四头肌等', max_length=100, verbose_name='肌肉部位名称')),
                ('latin_name', models.CharField(blank=True, help_text='肌肉部位的拉丁学名', max_length=100, null=True, verbose_name='拉丁学名')),
                ('image', models.ImageField(blank=True, help_text='上传肌肉部位的图片', null=True, upload_to='muscle_images/', verbose_name='肌肉图片')),
                ('video_url', models.URLField(blank=True, help_text='输入相关的训练视频链接', max_length=500, null=True, verbose_name='视频链接')),
                ('description', models.TextField(help_text='详细描述该肌肉的位置、功能和训练方法', verbose_name='详细描述')),
                ('training_tips', models.TextField(blank=True, help_text='输入该肌肉的训练要点和注意事项', null=True, verbose_name='训练要点')),
                ('is_featured', models.BooleanField(default=False, help_text='勾选后在首页推荐显示', verbose_name='推荐显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_items', to='fitness_guide.musclegroup', verbose_name='所属肌肉群')),
            ],
            options={
                'verbose_name': '肌肉部位',
                'verbose_name_plural': '肌肉部位列表',
                'ordering': ['muscle_group', 'name'],
            },
        ),
    ]
