# Generated by Django 4.2 on 2026-04-27 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('condition_type', models.CharField(choices=[('total_sessions', '累计训练次数'), ('streak_days', '连续训练天数'), ('total_xp', '累计经验值'), ('first_session', '首次训练'), ('plan_master', '完成所有训练方案'), ('night_owl', '深夜训练'), ('gentle_soul', '完成舒缓训练')], max_length=30)),
                ('condition_value', models.IntegerField(default=1)),
                ('xp_reward', models.IntegerField(default=50)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('mood_tag', models.CharField(choices=[('anxious', '焦虑舒缓'), ('low_energy', '低能量唤醒'), ('normal', '日常保持'), ('night', '夜间放松')], default='normal', max_length=20)),
                ('space_tag', models.CharField(choices=[('dorm', '宿舍模式'), ('room', '房间模式'), ('any', '任意空间')], default='any', max_length=20)),
                ('silent_mode', models.BooleanField(default=True)),
                ('icon', models.CharField(default='🏠', max_length=50)),
                ('xp_reward', models.IntegerField(default=30)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'duration_minutes'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_mode', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=True)),
                ('low_social_mode', models.BooleanField(default=False)),
                ('preferred_coach_type', models.CharField(choices=[('calm', '冷静型'), ('rational', '理性型'), ('light_tsukkomi', '轻吐槽型')], default='calm', max_length=20)),
                ('do_not_disturb', models.BooleanField(default=True)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_training_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', '已完成'), ('partial', '部分完成'), ('skipped', '已跳过')], default='completed', max_length=20)),
                ('xp_earned', models.IntegerField(default=0)),
                ('exercises_completed', models.IntegerField(default=0)),
                ('exercises_total', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.trainingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration_seconds', models.IntegerField(help_text='单个动作时长（秒）')),
                ('voice_guide', models.TextField(blank=True, help_text='语音引导文案')),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.trainingplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
