# Generated by Django 4.2 on 2026-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='reward_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='reward_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
