# Generated by Django 5.1.4 on 2026-03-09 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sleep_time', models.TimeField(help_text='入睡时间')),
                ('wake_time', models.TimeField(help_text='起床时间')),
                ('quality', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], default='fair', max_length=20)),
                ('duration', models.FloatField(blank=True, help_text='睡眠时长（小时）', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
