# Generated by Django 4.2 on 2026-04-22 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_background', models.ImageField(blank=True, help_text='上传自定义背景图片，支持 JPG、PNG 格式', null=True, upload_to='backgrounds/', verbose_name='自定义背景图片')),
                ('use_custom_background', models.BooleanField(default=False, help_text='开启后将使用上传的图片作为背景', verbose_name='使用自定义背景')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
