# Generated by Django 4.2 on 2026-04-27 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='运动名称')),
                ('category', models.CharField(choices=[('home', '🏠 居家训练'), ('outdoor', '🏃 户外运动'), ('gym', '🏋️ 器械训练'), ('cardio', '❤️ 有氧燃脂'), ('stretch', '🧘 拉伸放松')], max_length=20, verbose_name='运动类别')),
                ('difficulty', models.CharField(choices=[('beginner', '入门'), ('intermediate', '进阶'), ('challenge', '挑战')], default='beginner', max_length=20, verbose_name='难度')),
                ('calories_per_minute', models.FloatField(default=5.0, verbose_name='每分钟消耗卡路里')),
                ('icon', models.CharField(default='💪', max_length=50, verbose_name='图标')),
                ('strength_gain', models.IntegerField(default=1, verbose_name='力量增长')),
                ('endurance_gain', models.IntegerField(default=1, verbose_name='耐力增长')),
                ('agility_gain', models.IntegerField(default=0, verbose_name='敏捷增长')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '运动类型',
                'verbose_name_plural': '运动类型列表',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-date', '-time'], 'verbose_name': '运动打卡', 'verbose_name_plural': '运动打卡记录'},
        ),
        migrations.AddField(
            model_name='checkin',
            name='calories_burned',
            field=models.IntegerField(blank=True, help_text='该次运动消耗的卡路里（自动计算或手动输入）', null=True, verbose_name='消耗卡路里'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='activity',
            field=models.CharField(help_text='输入运动项目名称，如"跑步"、"游泳"、"健身"等', max_length=100, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='打卡日期'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='duration',
            field=models.IntegerField(help_text='输入活动持续时间，单位为分钟', verbose_name='活动时长（分钟）'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS纬度坐标，可通过地图获取', null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='location',
            field=models.CharField(blank=True, help_text='输入位置名称，如"XX健身房"、"XX公园"', max_length=200, null=True, verbose_name='位置描述'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS经度坐标，可通过地图获取', null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='notes',
            field=models.TextField(blank=True, help_text='添加任何其他想记录的信息', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='打卡时间'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='exercise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='checkin.exercisetype', verbose_name='运动类型'),
        ),
    ]
