# Generated by Django 4.2 on 2026-04-27 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.TextField(verbose_name='成就描述')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='图标')),
                ('category', models.CharField(choices=[('checkin', '打卡成就'), ('meal', '饮食成就'), ('sleep', '睡眠成就'), ('social', '趣味成就'), ('special', '特殊成就')], max_length=20, verbose_name='分类')),
                ('xp_reward', models.IntegerField(default=50, verbose_name='经验奖励')),
                ('condition_type', models.CharField(max_length=50, verbose_name='条件类型')),
                ('condition_value', models.IntegerField(default=1, verbose_name='条件数值')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='隐藏成就')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就列表',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('mission_type', models.CharField(choices=[('checkin', '运动打卡'), ('duration', '运动时长'), ('meal', '三餐记录'), ('sleep', '早睡挑战')], max_length=20, verbose_name='任务类型')),
                ('target_value', models.IntegerField(default=1, verbose_name='目标值')),
                ('xp_reward', models.IntegerField(default=30, verbose_name='经验奖励')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '每日任务',
                'verbose_name_plural': '每日任务列表',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserGameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0, verbose_name='经验值')),
                ('level', models.IntegerField(default=1, verbose_name='等级')),
                ('strength', models.IntegerField(default=1, verbose_name='力量')),
                ('endurance', models.IntegerField(default=1, verbose_name='耐力')),
                ('agility', models.IntegerField(default=1, verbose_name='敏捷')),
                ('willpower', models.IntegerField(default=1, verbose_name='意志')),
                ('total_checkins', models.IntegerField(default=0, verbose_name='总打卡次数')),
                ('total_exercise_minutes', models.IntegerField(default=0, verbose_name='总运动时长(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户游戏档案',
                'verbose_name_plural': '用户游戏档案列表',
            },
        ),
        migrations.CreateModel(
            name='UserDailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('progress', models.IntegerField(default=0, verbose_name='当前进度')),
                ('completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_system.dailymission', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_missions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户每日任务',
                'verbose_name_plural': '用户每日任务列表',
                'unique_together': {('user', 'mission', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解锁时间')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_system.achievement', verbose_name='成就')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就列表',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
